Upgrade dependencies, improve projects, add talk with pdf images example (#10)
* refactor: remove src on package imports

* fix: add os path

* refactor: add session approach to integration mcp

* feat: restructure project again after adding build settings

* feat: add mongo atlas db

* fix: retrieval errors

* feat: upgrade deps, fix after upgrades, add pdf example

* feat: add logging, fix some incorrect names

diff --git a/ai/langgraph/code/playground/Makefile b/ai/langgraph/code/playground/Makefile
--- a/ai/langgraph/code/playground/Makefile
+++ b/ai/langgraph/code/playground/Makefile
@@ -1,14 +1,35 @@
 # GLOBAL
 ##########################################################################
 
-lint:
-	uv run ruff format . && uv run ruff check . --fix
+CHECK_DIRS := .
 
 check:
+	uv run ty check
+	uv run ruff check $(CHECK_DIRS)
+
+format:
+	uv run ruff format $(CHECK_DIRS)
+
+fixes:
+	uv run ruff format $(CHECK_DIRS)
+	uv run ruff check $(CHECK_DIRS) --fix
 	uv run ty check
 
 sync:
 	uv sync
+
+# INFRA
+##########################################################################
+
+infra-up:
+	@if ! docker compose -p py-playground up --remove-orphans --wait; then \
+        		echo "Failed to start containers"; \
+        		docker compose -p py-playground logs; \
+        		exit 1; \
+    	fi
+
+infra-down:
+	docker-compose -p py-playground down
 
 # BASICS
 ##########################################################################
@@ -64,3 +85,5 @@ mcp-github:
 stocks-chatbot:
 	uv run python -m src.examples.stocks_chatbot.main
 
+spy-signals:
+	uv run python -m src.examples.spy_signals.main
